### ISSUE TITLE
When using "import" command, could we treat the import  json files "As Is" (example included below)

### ISSUE THREAD

**Issue by jdschleicher** [texei/texei-sfdx-plugin#124]
hi! love the plugin and use it for many things.

(side note, not sure if its just me, but in order to get debugging working for the plugin i had to change the oclif.commands property in the package.json at the root of the project. In master it is "lib/commands" and I had to change it to "src/commands")

When using scratch orgs I usually have an idea and also a limit on how many Users I can create or reference so if I create data files it's not too much of a lift to introduce a variable that hard codes the user id to all user lookups. I also may want to leverage an existing parent record Id for a lookup. Either case I would love the ability to have an expected data plan of fields and associated values and be treated "as is". 

Here is an example of what I'm trying to get working. As long as there is a hardcoded Id there for any lookup field I would want to use that: 

![image](https://user-images.githubusercontent.com/3968818/231790810-5b4e96ac-f02f-4e04-be82-1e76d91f28db.png)

let me know what you all think, maybe there is a configuration we can play with in the data-plan.json? I see "lookupOverrides" in the code but I couldn't quite figure it out or come across any associated documentation. 

Here is an update I've been playing around with from the import.ts:

```typescript
   // Regular lookups
          if (sobject[lookup.name] && !(  sobjectName === 'PricebookEntry' 
                                            && sobject.Pricebook2Id === 'StandardPriceBook' 
                                            && lookup.name === 'Pricebook2Id') ) {


              // only if look up field has syntax keyword "ref", then replace with existing record
              // this "ref" match reflects an expected "referenceId"
              // we could create a map of expected "referenceIds" and only if lookup name is included 
              // then replace with result from recordsIdMap. 
              // This would allow for hardcoded and expected record Ids to work "as is"
              if ( (sobject[lookup.name].toLowerCase().includes("ref")) ) {

                sobject[lookup.name] = recordIdsMap.get(sobject[lookup.name]);

              }          

          }
```

**Comment by FabienTaillon** [comment]
Well, `lookupOverride` is something we haven't documented yet, but just because we're late on the documentation. The feature itself is already working.
The idea is to define an object, and for each lookup of this type, to use a mapping of fields as key to map to existing records in the org.

So you'll need to use a data plan file (`sfdx texei:data:plan:generate`), and define which fields to use for any lookup related to a User:

```
{
  "excludedFields": [],
  "lookupOverride": {
    "User": "Id"
  },
  "sObjects": [
    {
      "name": "Account",
      "label": "",
      "filters": "",
      "orderBy": "",
      "externalId": "",
      "excludedFields": []
    }
  ]
}
```

You would need to export the data with this data plan, and then import it and it would work.

The feature is designed to import some data at Scratch Org creation in a pool, and then when a developer needs to push some other data on the fly, being able to map the existing records to the one from

So for instance let's say you already created some Users, and on a later import you want to remap them, Id and username may be different from the source org, but you could define that using `FirstName`, `LastName` and `Email` you'll always be able to find a unique user. You'll setup the `lookupOverride` like this:

```
{
  "excludedFields": [],
  "lookupOverride": {
    "User": "FirstName,LastName,Email"
  },
  "sObjects": [
    {
      "name": "Account",
      "label": "",
      "filters": "",
      "orderBy": "",
      "externalId": "",
      "excludedFields": []
    }
  ]
}
```

And then, for all exported user lookup fields on any object, it would remap on the fly at import with the correct user, even if Id and username has changed from one scratch org to another.

That's not 100% what you need, as to be able to do that the command will retrieve almost all user data from the scratch org to be able to compare FirstName, LastName and Email, but if you have only a few thousand records that should be fast anyway. And you should not have to bother about Ids anymore.

**Comment by FabienTaillon** [comment]
And thanks for sharing that you love our plugin ! :)
