### ISSUE TITLE
Error exporting PermissionSetLicense

### ISSUE THREAD

**Issue by chris-sfdc** [texei/texei-sfdx-plugin#33]
When attempting to export records from the PermissionSetLicense table (in order to use them for a later import of PermissionSetLicenseAssign records), the following error is encountered:

`ERROR running texei:data:export:  `
`                         FROM PermissionSetLicense`
`                        ^`
`ERROR at Row:2:Column:25`
`unexpected token: 'FROM'`

Potentially this sObject is not available through the API being used?

**Comment by FabienTaillon** [comment]
@chris-sfdc it doesn't work because the PermissionSetLicense object isn't creatable: https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_permissionsetlicense.htm

@chris-sfdc The command only export creatable fields, as the goal is to import them later.

I'll add a better error message.

That being said, I understand that you're mostly in the relationship, more than the PermissionSetLicense.
What's you're exact use case ? Is it for development in a Scratch Org ? To populate data from a sandbox to another ? Does it mean you're also exporting/importing users ?

**Comment by chris-sfdc** [comment]
Thanks for the reply, @FabienTaillon. We worked around this and from my perspective just adding a clearer message is all it needs. 

But to answer your question, the use case is indeed for development in a scratch org, with the process being:

1. Create user through a script
2. Get the PermissionSetLicense from the org
3. Import a PermissionSetLicense assignment to give that PSL to the user

**Comment by FabienTaillon** [comment]
Ok thanks, I've added an error message in [v1.10.0](https://github.com/texei/texei-sfdx-plugin/releases/tag/v1.10.0).
