### ISSUE TITLE
texei:skinnyprofile:retrieve requires Dev Hub username

### ISSUE THREAD

**Issue by rjfay** [texei/texei-sfdx-plugin#46]
Hi @FabienTaillon 

Thanks for sharing this plugin - looks very useful.  

**Context**
I've just tried to run `sfdx texei:skinnyprofile:retrieve` in a project that has a default username but no dev hub.  I also tried adding `-u myDefaultUser`, with the same result.

**Expected**
I expect this to execute the command against the default user, or against the user given by the -u flag

**Actual**
The plugin returns the error `This command requires a dev hub org username set either with a flag or by default in the config`.

I assume this is because `requiresDevhubUsername` is set to `true` in https://github.com/texei/texei-sfdx-plugin/blob/5937f465bfaf448bfb0235ea645407aebd7ef622/src/commands/texei/skinnyprofile/retrieve.ts#L44

Please consider changing this assignment so that the command does not require a DevHub for the project.

**Comment by FabienTaillon** [comment]
You're right, this doesn't make sense.

**Comment by FabienTaillon** [comment]
This is fixed.

Note that there is no real doc for this command so far, but the idea behind it is to retrieve everything that can't be in a Permission Set (Page Layout assignments, default record types, default app), and remove everything else. 
The command is based on what's in your repo, so if you add a page layout, you should pull it before running the command, otherwise assignment won't be added to the profile metadata.

There is one issue remaining: when you create a new profile, Salesforce automatically check some permissions, so the first time you'll deploy a profile you may see some access rights that were not part of the metadata. This is on creation only. I think at some point to try to improve the command by setting these access rights to false in the metadata.

**Comment by rjfay** [comment]
Thanks for explaining, @FabienTaillon.

This would also be useful for permission sets - i.e. the ability to reconcile the permission set against the repo and remove references that are not in there.

**Comment by FabienTaillon** [comment]
Well Permission Set is supposed to work already correctly with the Metadata API. Are you seeing any issues ? Are you on Scratch Org (if so, what is in the org/permission set that isn't in the repo ?)
